import { Montserrat } from "next/font/google";
import "./globals.css";
import AddBootstrap from "./AddBootstrap.js";
import "bootstrap/dist/css/bootstrap.min.css";

const montserrat = Montserrat({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable}`}
        style={{ fontFamily: "montserrat" }}
      >
        <AddBootstrap />
        {children}
      </body>
    </html>
  );
}
